# frozen_string_literal: true

# == Schema Information
#
# Table name: foods
#
#  id                                              :integer          not null, primary key
#  acetic_acid                                     :decimal(10, 4)
#  added_sugars                                    :decimal(10, 4)
#  alanine_mg                                      :decimal(10, 4)
#  alanine_mg_gn                                   :decimal(10, 4)
#  alcohol                                         :decimal(10, 4)
#  alpha_carotene                                  :decimal(10, 4)
#  alpha_tocopherol                                :decimal(10, 4)
#  alpha_tocotrienol                               :decimal(10, 4)
#  aluminium_al                                    :decimal(10, 4)
#  antimony_sb                                     :decimal(10, 4)
#  arginine_mg                                     :decimal(10, 4)
#  arginine_mg_gn                                  :decimal(10, 4)
#  arsenic_as                                      :decimal(10, 4)
#  ash                                             :decimal(10, 4)
#  aspartic_acid_mg                                :decimal(10, 4)
#  aspartic_acid_mg_gn                             :decimal(10, 4)
#  available_carbohydrate_with_sugar_alcohols      :decimal(10, 4)
#  available_carbohydrate_without_sugar_alcohols   :decimal(10, 4)
#  beta_carotene                                   :decimal(10, 4)
#  beta_carotene_equivalents_provitamin_a          :decimal(10, 4)
#  beta_tocopherol                                 :decimal(10, 4)
#  beta_tocotrienol                                :decimal(10, 4)
#  biotin_b7                                       :decimal(10, 4)
#  c10_g                                           :decimal(10, 4)
#  c10_t                                           :decimal(10, 4)
#  c11_g                                           :decimal(10, 4)
#  c11_t                                           :decimal(10, 4)
#  c12_1_g                                         :decimal(10, 4)
#  c12_1_t                                         :decimal(10, 4)
#  c12_2_g                                         :decimal(10, 4)
#  c12_2_t                                         :decimal(10, 4)
#  c12_g                                           :decimal(10, 4)
#  c12_t                                           :decimal(10, 4)
#  c13_g                                           :decimal(10, 4)
#  c13_t                                           :decimal(10, 4)
#  c14_1_g                                         :decimal(10, 4)
#  c14_1_t                                         :decimal(10, 4)
#  c14_g                                           :decimal(10, 4)
#  c14_t                                           :decimal(10, 4)
#  c15_1_g                                         :decimal(10, 4)
#  c15_1_t                                         :decimal(10, 4)
#  c15_g                                           :decimal(10, 4)
#  c15_t                                           :decimal(10, 4)
#  c16_1_g                                         :decimal(10, 4)
#  c16_1_t                                         :decimal(10, 4)
#  c16_2w4_mg                                      :decimal(10, 4)
#  c16_2w4_t                                       :decimal(10, 4)
#  c16_3_g                                         :decimal(10, 4)
#  c16_3_t                                         :decimal(10, 4)
#  c16_g                                           :decimal(10, 4)
#  c16_t                                           :decimal(10, 4)
#  c17_1_g                                         :decimal(10, 4)
#  c17_1_t                                         :decimal(10, 4)
#  c17_g                                           :decimal(10, 4)
#  c17_t                                           :decimal(10, 4)
#  c18_1_g                                         :decimal(10, 4)
#  c18_1_t                                         :decimal(10, 4)
#  c18_1w7_g                                       :decimal(10, 4)
#  c18_1w7_t                                       :decimal(10, 4)
#  c18_2w6_g                                       :decimal(10, 4)
#  c18_2w6_t                                       :decimal(10, 4)
#  c18_3w3_g                                       :decimal(10, 4)
#  c18_3w3_t                                       :decimal(10, 4)
#  c18_3w4_g                                       :decimal(10, 4)
#  c18_3w4_t                                       :decimal(10, 4)
#  c18_3w6_mg                                      :decimal(10, 4)
#  c18_3w6_t                                       :decimal(10, 4)
#  c18_4w1_g                                       :decimal(10, 4)
#  c18_4w1_t                                       :decimal(10, 4)
#  c18_4w3_mg                                      :decimal(10, 4)
#  c18_4w3_t                                       :decimal(10, 4)
#  c18_g                                           :decimal(10, 4)
#  c18_t                                           :decimal(10, 4)
#  c19_g                                           :decimal(10, 4)
#  c19_t                                           :decimal(10, 4)
#  c20_1_g                                         :decimal(10, 4)
#  c20_1_t                                         :decimal(10, 4)
#  c20_1w11_mg                                     :decimal(10, 4)
#  c20_1w11_t                                      :decimal(10, 4)
#  c20_2_mg                                        :decimal(10, 4)
#  c20_2_t                                         :decimal(10, 4)
#  c20_2w6_mg                                      :decimal(10, 4)
#  c20_2w6_t                                       :decimal(10, 4)
#  c20_3                                           :decimal(10, 4)
#  c20_3w3_mg                                      :decimal(10, 4)
#  c20_3w3_t                                       :decimal(10, 4)
#  c20_3w6_mg                                      :decimal(10, 4)
#  c20_3w6_t                                       :decimal(10, 4)
#  c20_4_g                                         :decimal(10, 4)
#  c20_4_t                                         :decimal(10, 4)
#  c20_4w3_mg                                      :decimal(10, 4)
#  c20_4w3_t                                       :decimal(10, 4)
#  c20_4w6_mg                                      :decimal(10, 4)
#  c20_4w6_t                                       :decimal(10, 4)
#  c20_5w3_mg                                      :decimal(10, 4)
#  c20_5w3_t                                       :decimal(10, 4)
#  c20_g                                           :decimal(10, 4)
#  c20_t                                           :decimal(10, 4)
#  c21_5w3_g                                       :decimal(10, 4)
#  c21_5w3_t                                       :decimal(10, 4)
#  c21_g                                           :decimal(10, 4)
#  c21_t                                           :decimal(10, 4)
#  c22_1_g                                         :decimal(10, 4)
#  c22_1_t                                         :decimal(10, 4)
#  c22_1w11_mg                                     :decimal(10, 4)
#  c22_1w11_t                                      :decimal(10, 4)
#  c22_2_g                                         :decimal(10, 4)
#  c22_2_t                                         :decimal(10, 4)
#  c22_2w6_mg                                      :decimal(10, 4)
#  c22_2w6_t                                       :decimal(10, 4)
#  c22_4w6_mg                                      :decimal(10, 4)
#  c22_4w6_t                                       :decimal(10, 4)
#  c22_5w3_mg                                      :decimal(10, 4)
#  c22_5w3_t                                       :decimal(10, 4)
#  c22_5w6_g                                       :decimal(10, 4)
#  c22_5w6_t                                       :decimal(10, 4)
#  c22_6w3_mg                                      :decimal(10, 4)
#  c22_6w3_t                                       :decimal(10, 4)
#  c22_g                                           :decimal(10, 4)
#  c22_t                                           :decimal(10, 4)
#  c23_g                                           :decimal(10, 4)
#  c23_t                                           :decimal(10, 4)
#  c24_1_g                                         :decimal(10, 4)
#  c24_1_t                                         :decimal(10, 4)
#  c24_g                                           :decimal(10, 4)
#  c24_t                                           :decimal(10, 4)
#  c4_g                                            :decimal(10, 4)
#  c4_t                                            :decimal(10, 4)
#  c6_g                                            :decimal(10, 4)
#  c6_t                                            :decimal(10, 4)
#  c8_g                                            :decimal(10, 4)
#  c8_t                                            :decimal(10, 4)
#  cadmium_cd                                      :decimal(10, 4)
#  caffeine                                        :decimal(10, 4)
#  calcium_ca                                      :decimal(10, 4)
#  chloride_cl                                     :decimal(10, 4)
#  cholecalciferol_d3                              :decimal(10, 4)
#  cholesterol                                     :decimal(10, 4)
#  chromium_cr                                     :decimal(10, 4)
#  citric_acid                                     :decimal(10, 4)
#  classification                                  :string
#  cobalamin_b12                                   :decimal(10, 4)
#  cobalt_co                                       :decimal(10, 4)
#  copper_cu                                       :decimal(10, 4)
#  cryptoxanthin                                   :decimal(10, 4)
#  cystine_plus_cysteine_mg                        :decimal(10, 4)
#  cystine_plus_cysteine_mg_gn                     :decimal(10, 4)
#  delta_tocopherol                                :decimal(10, 4)
#  delta_tocotrienol                               :decimal(10, 4)
#  derivation                                      :string
#  dextrin                                         :decimal(10, 4)
#  dietary_folate_equivalents                      :decimal(10, 4)
#  energy_with_dietary_fibre_equated               :integer
#  energy_without_dietary_fibre_equated            :integer
#  ergocalciferol_d2                               :decimal(10, 4)
#  erythritol                                      :decimal(10, 4)
#  fat_total                                       :decimal(10, 4)
#  fluoride_f                                      :decimal(10, 4)
#  folate_natural                                  :decimal(10, 4)
#  folic_acid                                      :decimal(10, 4)
#  food_name                                       :string
#  free_sugars                                     :decimal(10, 4)
#  fructose                                        :decimal(10, 4)
#  fumaric_acid                                    :decimal(10, 4)
#  galactose                                       :decimal(10, 4)
#  gamma_tocopherol                                :decimal(10, 4)
#  gamma_tocotrienol                               :decimal(10, 4)
#  glucose                                         :decimal(10, 4)
#  glutamic_acid_mg                                :decimal(10, 4)
#  glutamic_acid_mg_gn                             :decimal(10, 4)
#  glycerol                                        :decimal(10, 4)
#  glycine_mg                                      :decimal(10, 4)
#  glycine_mg_gn                                   :decimal(10, 4)
#  glycogen                                        :decimal(10, 4)
#  histidine_mg                                    :decimal(10, 4)
#  histidine_mg_gn                                 :decimal(10, 4)
#  hydroxy_cholecalciferol_25_oh_d3                :decimal(10, 4)
#  hydroxy_ergocalciferol_25_oh_d2                 :decimal(10, 4)
#  inulin                                          :decimal(10, 4)
#  iodine_i                                        :decimal(10, 4)
#  iron_fe                                         :decimal(10, 4)
#  isoleucine_mg                                   :decimal(10, 4)
#  isoleucine_mg_gn                                :decimal(10, 4)
#  lactic_acid                                     :decimal(10, 4)
#  lactose                                         :decimal(10, 4)
#  lead_pb                                         :decimal(10, 4)
#  leucine_mg                                      :decimal(10, 4)
#  leucine_mg_gn                                   :decimal(10, 4)
#  lutein                                          :decimal(10, 4)
#  lycopene                                        :decimal(10, 4)
#  lysine_mg                                       :decimal(10, 4)
#  lysine_mg_gn                                    :decimal(10, 4)
#  magnesium_mg                                    :decimal(10, 4)
#  malic_acid                                      :decimal(10, 4)
#  maltitol                                        :decimal(10, 4)
#  maltodextrin                                    :decimal(10, 4)
#  maltose                                         :decimal(10, 4)
#  manganese_mn                                    :decimal(10, 4)
#  mannitol                                        :decimal(10, 4)
#  mercury_hg                                      :decimal(10, 4)
#  methionine_mg                                   :decimal(10, 4)
#  methionine_mg_gn                                :decimal(10, 4)
#  moisture_water                                  :decimal(10, 4)
#  molybdenum_mo                                   :decimal(10, 4)
#  niacin_b3                                       :decimal(10, 4)
#  niacin_derived_equivalents                      :decimal(10, 4)
#  niacin_derived_from_tryptophan                  :decimal(10, 4)
#  nickel_ni                                       :decimal(10, 4)
#  nitrogen                                        :decimal(10, 4)
#  oligosaccharides                                :decimal(10, 4)
#  oxalic_acid                                     :decimal(10, 4)
#  pantothenic_acid_b5                             :decimal(10, 4)
#  phenylalanine_mg                                :decimal(10, 4)
#  phenylalanine_mg_gn                             :decimal(10, 4)
#  phosphorus_p                                    :decimal(10, 4)
#  polydextrose                                    :decimal(10, 4)
#  potassium_k                                     :decimal(10, 4)
#  proline_mg                                      :decimal(10, 4)
#  proline_mg_gn                                   :decimal(10, 4)
#  propionic_acid                                  :decimal(10, 4)
#  protein                                         :decimal(10, 4)
#  public_food_key                                 :string           not null
#  pyridoxine_b6                                   :decimal(10, 4)
#  quinic_acid                                     :decimal(10, 4)
#  raffinose                                       :decimal(10, 4)
#  resistant_starch                                :decimal(10, 4)
#  retinol_preformed_vitamin_a                     :decimal(10, 4)
#  riboflavin_b2                                   :decimal(10, 4)
#  selenium_se                                     :decimal(10, 4)
#  serine_mg                                       :decimal(10, 4)
#  serine_mg_gn                                    :decimal(10, 4)
#  shikimic_acid                                   :decimal(10, 4)
#  sodium_na                                       :decimal(10, 4)
#  sorbitol                                        :decimal(10, 4)
#  stachyose                                       :decimal(10, 4)
#  starch                                          :decimal(10, 4)
#  succinic_acid                                   :decimal(10, 4)
#  sucrose                                         :decimal(10, 4)
#  sulphur_s                                       :decimal(10, 4)
#  tartaric_acid                                   :decimal(10, 4)
#  thiamin_b1                                      :decimal(10, 4)
#  threonine_mg                                    :decimal(10, 4)
#  threonine_mg_gn                                 :decimal(10, 4)
#  tin_sn                                          :decimal(10, 4)
#  total_dietary_fibre                             :decimal(10, 4)
#  total_folates                                   :decimal(10, 4)
#  total_long_chain_omega_3_fatty_acids_equated_mg :decimal(10, 4)
#  total_long_chain_omega_3_fatty_acids_equated_t  :decimal(10, 4)
#  total_monounsaturated_fatty_acids_equated_g     :decimal(10, 4)
#  total_monounsaturated_fatty_acids_equated_t     :decimal(10, 4)
#  total_polyunsaturated_fatty_acids_equated_g     :decimal(10, 4)
#  total_polyunsaturated_fatty_acids_equated_t     :decimal(10, 4)
#  total_saturated_fatty_acids_equated_g           :decimal(10, 4)
#  total_saturated_fatty_acids_equated_t           :decimal(10, 4)
#  total_sugars                                    :decimal(10, 4)
#  total_trans_fatty_acids_imputed_mg              :decimal(10, 4)
#  total_trans_fatty_acids_imputed_t               :decimal(10, 4)
#  total_undifferentiated_fatty_acids              :decimal(10, 4)
#  total_undifferentiated_fatty_acids_mass_basis   :decimal(10, 4)
#  tryptophan_mg                                   :decimal(10, 4)
#  tryptophan_mg_gn                                :decimal(10, 4)
#  tyrosine_mg                                     :decimal(10, 4)
#  tyrosine_mg_gn                                  :decimal(10, 4)
#  valine_mg                                       :decimal(10, 4)
#  valine_mg_gn                                    :decimal(10, 4)
#  vitamin_a_retinol_equivalents                   :decimal(10, 4)
#  vitamin_c                                       :decimal(10, 4)
#  vitamin_d3_equivalents                          :decimal(10, 4)
#  vitamin_e                                       :decimal(10, 4)
#  xanthophyl                                      :decimal(10, 4)
#  xylitol                                         :decimal(10, 4)
#  zinc_zn                                         :decimal(10, 4)
#  created_at                                      :datetime         not null
#  updated_at                                      :datetime         not null
#
# Indexes
#
#  index_foods_on_classification   (classification)
#  index_foods_on_food_name        (food_name)
#  index_foods_on_public_food_key  (public_food_key) UNIQUE
#
class Food < ApplicationRecord
  def as_json(verbose: false)
    if verbose
      attributes.except("id", "created_at", "updated_at").compact
    else
      attributes.slice(
        "public_food_key", "food_name", "classification",
        "energy_with_dietary_fibre_equated", "protein", "fat_total",
        "available_carbohydrate_without_sugar_alcohols", "total_dietary_fibre"
      ).compact
    end
  end
end
